version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@5.2.0
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - eb/deploy:
          context: aws-creds
          environment-name: Getting-env
          filters:
            branches:
              only:
                - main
          label: getting-version-6
          application-name: getting
